repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-ast

  - repo: https://github.com/asottile/pyupgrade
    rev: master
    hooks:
      - id: pyupgrade

  - repo: local
    hooks:
      - id: mypy
        name: run mypy
        language: system
        entry: bash -c 'poetry run mypy "$@"' --
        types: [python]

      - id: flake8
        name: run flake8
        language: system
        entry: bash -c 'poetry run flake8 "$@"' --
        types: [python]

      - id: isort
        name: run isort
        language: system
        entry: bash -c 'poetry run isort "$@"' --
        types: [python]

      - id: black
        name: run black
        language: system
        entry: bash -c 'poetry run black "$@"' --
        types: [python]
