name: Preview infrastructure

on:
  pull_request:
    paths:
      - "infrastructure/**/*"
      - "infrastructure/*"

jobs:
  preview:
    name: Preview changes
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./infrastructure
    steps:
      - uses: actions/checkout@v2
      - name: Prepare venv
        run: |
          python3 -m venv ./venv
          ./venv/bin/python -m pip install --upgrade pip setuptools wheel
          ./venv/bin/python -m pip install -r requirements.txt
      - name: Select production stack
        run: pulumi stack select production
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: eu-central-1
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      - name: Configure secrets
        run: |
          pulumi config set --secret SLACK_BOT_TOKEN ${{ secrets.SLACK_BOT_TOKEN }}
          pulumi config set --secret SLACK_SIGNING_SECRET ${{ secrets.SLACK_SIGNING_SECRET }}
          pulumi config set --secret IFFFT_WEBHOOK ${{ secrets.IFFFT_WEBHOOK }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: eu-central-1
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      - name: Preview
        run: pulumi preview
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: eu-central-1
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
